### ISSUE TITLE
Slash commands aren't created in the client

### ISSUE THREAD

**Issue by thewilloftheshadow** [almostSouji/github-interaction-worker#3]
When deploying this to Cloudflare for a new guild, the slash commands aren't created in Discord, rendering the worker useless until it is manually created

**Comment by almostSouji** [comment]
Correct, as this was a small project for just one server to use I have not built any utility to deploy commands. It is simply a matter of a single request, where the JSON body is provided in the model file in the root directory.

More info on how to deploy commands via REST requests  (be that in-app or via a rest client like thunder, insomnia or postman) can be found on the discord dev docs: <https://discord.com/developers/docs/interactions/slash-commands#bulk-overwrite-global-application-commands>
